analytics: {}
color:
  brandColors:
    - '#000000'
    - '#003868'
    - '#000000'
    - '#28A0D8'
    - '#A0C8F0'
  brandStrength: 0.495066
  lightness: 0.129934
  rhythmicContrast: 0.251645
  saturation: 0.830967
cta: {}
layout_spectrum: 0.944901
name: The Center Point
opengraph: {}
purpose: {}
typography_spectrum: 0.264803
